export const feedbackDataTwo = [
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user10.jpg",
        name: "Caryn Zoeller",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user11.jpg",
        name: "Jill Brooks",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user12.jpg",
        name: "Fredric Kilgore",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user13.jpg",
        name: "Viola Normandin",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user10.jpg",
        name: "Caryn Zoeller",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user11.jpg",
        name: "Jill Brooks",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user12.jpg",
        name: "Fredric Kilgore",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user13.jpg",
        name: "Viola Normandin",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user10.jpg",
        name: "Caryn Zoeller",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user11.jpg",
        name: "Jill Brooks",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user12.jpg",
        name: "Fredric Kilgore",
        designation: "Ex-Student",
    },
    {
        rating: "/images/icons/stars-5.svg",
        feedback: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
        image: "/images/users/user13.jpg",
        name: "Viola Normandin",
        designation: "Ex-Student",
    },
]